quarkus.http.port=8081

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.incoming.notification-in.connector=smallrye-kafka
mp.messaging.incoming.notification-in.topic=notification
mp.messaging.incoming.notification-in.group.id=notification-service
mp.messaging.incoming.notification-in.auto.offset.reset=earliest
mp.messaging.incoming.notification-in.value.deserializer=dev.pedro.retrydlq.notification.event.OrderConfirmedDeserializer
mp.messaging.incoming.notification-in.failure-strategy=fail

mp.messaging.outgoing.notification-dlq-out.connector=smallrye-kafka
mp.messaging.outgoing.notification-dlq-out.topic=notification-dlq
mp.messaging.outgoing.notification-dlq-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.notification-dlq-in.connector=smallrye-kafka
mp.messaging.incoming.notification-dlq-in.topic=notification-dlq
mp.messaging.incoming.notification-dlq-in.group.id=notification-dlq-admin
mp.messaging.incoming.notification-dlq-in.auto.offset.reset=earliest
mp.messaging.incoming.notification-dlq-in.value.deserializer=dev.pedro.retrydlq.notification.dlq.FailedNotificationDeserializer
