quarkus.http.port=8080

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.outgoing.notification-out.connector=smallrye-kafka
mp.messaging.outgoing.notification-out.topic=notification
mp.messaging.outgoing.notification-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
